SET statement_timeout = 0;

--==============================================================================
--bun:split

CREATE TABLE "sequence_nodes" (
    "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
);

--==============================================================================
--bun:split

CREATE TABLE "nodes" (
    "id" integer PRIMARY KEY REFERENCES "sequence_nodes"("id") ON DELETE CASCADE,
    "parent_id" integer NOT NULL DEFAULT 0,
    "name" varchar NOT NULL,
    "label" varchar,
    "uri" varchar,
    "path" varchar NOT NULL,
    "level" integer NOT NULL DEFAULT 0,
    "position" integer NOT NULL DEFAULT 0,
    "display_children" boolean NOT NULL DEFAULT true,
    "display" boolean NOT NULL DEFAULT true,
    "attributes" jsonb NOT NULL DEFAULT '{}',
    "link_attributes" jsonb NOT NULL DEFAULT '{}',
    "children_attributes" jsonb NOT NULL DEFAULT '{}',
    "label_attributes" jsonb NOT NULL DEFAULT '{}',
    "metadata" jsonb NOT NULL DEFAULT '{}',
    "created" timestamptz NOT NULL DEFAULT now(),
    "updated" timestamptz NOT NULL DEFAULT now()
);

--bun:split

CREATE INDEX "nodes_created_updated_idx" ON "nodes" ("created", "updated");
CREATE INDEX "nodes_path_idx" ON "nodes" ("path");
CREATE INDEX "nodes_level_idx" ON "nodes" ("level");
