SET statement_timeout = 0;

--==============================================================================
--bun:split

CREATE TABLE "pages" (
    "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "parent_id" integer REFERENCES "pages"("id") ON DELETE SET NULL,
    "site_id" integer REFERENCES "sites"("id") ON DELETE CASCADE,
    "name" varchar NOT NULL,
    "title" varchar,
    "pattern" varchar NOT NULL DEFAULT '_page_cms',
    "alias" varchar,
    "slug" varchar,
    "url" varchar,
    "custom_url" varchar,
    "template" varchar NOT NULL,
    "position" integer NOT NULL DEFAULT 0,
    "decorate" boolean NOT NULL DEFAULT true,
    "javascript" varchar,
    "stylesheet" varchar,
    "headers" jsonb NOT NULL DEFAULT '{}',
    "metas" jsonb NOT NULL DEFAULT '[]',
    "metadata" jsonb NOT NULL DEFAULT '{}',
    "created" timestamptz NOT NULL DEFAULT now(),
    "updated" timestamptz NOT NULL DEFAULT now(),
    "published" timestamptz,
    "expired" timestamptz
);

--bun:split

CREATE INDEX "pages_created_updated_idx" ON "pages" ("created", "updated");
CREATE INDEX "pages_published_expired_idx" ON "pages" ("published", "expired");
CREATE INDEX "pages_pattern_idx" ON "pages" ("pattern");
CREATE INDEX "pages_alias_idx" ON "pages" ("alias");
CREATE INDEX "pages_slug_idx" ON "pages" ("slug");
CREATE INDEX "pages_url_idx" ON "pages" ("url");
CREATE INDEX "pages_custom_url_idx" ON "pages" ("custom_url");
CREATE INDEX "pages_position_idx" ON "pages" ("position");
