SET statement_timeout = 0;

--==============================================================================
--bun:split

CREATE TABLE "sites" (
    "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar NOT NULL,
    "title" varchar,
    "separator" varchar NOT NULL DEFAULT ' - ',
    "host" varchar NOT NULL,
    "locale" varchar,
    "relative_path" varchar,
    "is_default" boolean NOT NULL DEFAULT false,
    "javascript" varchar,
    "stylesheet" varchar,
    "metas" jsonb NOT NULL DEFAULT '[]',
    "metadata" jsonb NOT NULL DEFAULT '{}',
    "created" timestamptz NOT NULL DEFAULT now(),
    "updated" timestamptz NOT NULL DEFAULT now(),
    "published" timestamptz,
    "expired" timestamptz
);

--bun:split

CREATE INDEX "sites_created_updated_idx" ON "sites" ("created", "updated");
CREATE INDEX "sites_published_expired_idx" ON "sites" ("published", "expired");
CREATE INDEX "sites_host_is_default_idx" ON "sites" ("host", "is_default");

--bun:split

CREATE UNIQUE INDEX "sites_host_lifespan_unq" ON "sites" (lower("host"),
                                                          lower(coalesce("locale", '')),
                                                          lower(coalesce("relative_path", '')),
                                                          coalesce("published", '1970-01-01 00:00:00.000'),
                                                          coalesce("expired", '1970-01-01 00:00:00.000'));
